const ADVENTURES=[...(window.ADVENTURES_1||[]),...(window.ADVENTURES_2||[]),...(window.ADVENTURES_3||[]),...(window.ADVENTURES_4||[]),...(window.ADVENTURES_5||[]),...(window.ADVENTURES_6||[]),...(window.ADVENTURES_7||[]),...(window.ADVENTURES_8||[]),...(window.ADVENTURES_9||[]),...(window.ADVENTURES_10||[])];
const get=(id)=>document.getElementById(id);
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);if(!raw)return fallback;return JSON.parse(raw)}catch(e){return fallback}}
function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){return false}}
const savedFavs=readJSON('cc_favorites',[]),savedDone=readJSON('cc_completed',[]),savedRatings=readJSON('cc_ratings',{});
let state={
 selected:null, cat:'all', favOnly:false,
 favorites:new Set(Array.isArray(savedFavs)?savedFavs:[]),
 completed:new Set(Array.isArray(savedDone)?savedDone:[]),
 ratings:new Map(Object.entries(savedRatings&&typeof savedRatings==='object'&&!Array.isArray(savedRatings)?savedRatings:{}).map(([k,v])=>[+k,v]))
};
function saveState(){writeJSON('cc_favorites',[...state.favorites]);writeJSON('cc_completed',[...state.completed]);writeJSON('cc_ratings',Object.fromEntries(state.ratings))}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.s===id));if(id==='saved')renderSaved();if(id==='passport')renderPassport()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{if(b.dataset.s==='scratch'&&!state.selected){randomPick();return}show(b.dataset.s)});
function timeGroup(t){t=(t||'').toLowerCase();if(t.includes('full'))return'full';if(t.includes('half'))return'half';return'short'}
function isFree(c){c=(c||'').toLowerCase();return c==='free'||c.startsWith('free')||c==='$'}
function easy(d){return (d||'').toLowerCase().includes('easy')}
function filtered(){let q=get('search').value.toLowerCase(),max=+get('drive').value,cost=get('cost').value,diff=get('difficulty').value,t=get('time').value,dog=get('dog').checked,unvisited=get('unvisited').checked;return ADVENTURES.filter(a=>(state.cat==='all'||a.categoryGroup===state.cat)&&a.drive<=max&&(cost==='any'||(cost==='free'?isFree(a.cost):!isFree(a.cost)))&&(diff==='any'||(diff==='easy'?easy(a.difficulty):!easy(a.difficulty)))&&(t==='any'||timeGroup(a.time)===t)&&(!dog||a.dogOk)&&(!unvisited||!state.completed.has(a.id))&&(!state.favOnly||state.favorites.has(a.id))&&(!q||(`${a.name} ${a.primary} ${a.town} ${a.category}`).toLowerCase().includes(q)))}
function renderList(){let arr=filtered();get('count').textContent=arr.length+' options';get('list').innerHTML=arr.map(a=>`<button class="card item" data-id="${a.id}"><div class="row"><div><div style="font-size:11px;text-transform:uppercase;letter-spacing:.1em" class="muted">${a.category}</div><div class="serif" style="font-size:21px">${a.name}</div><div class="muted" style="font-size:13px">${a.town}, ${a.state}</div></div><div style="text-align:right"><b>~${a.drive} min</b><div style="font-size:22px">${state.favorites.has(a.id)?'♥':'♡'}</div></div></div><div class="chips"><span class="chip">${a.time}</span><span class="chip">${a.cost}</span><span class="chip">${a.difficulty}</span><span class="chip">🐾 ${a.dog}</span>${state.completed.has(a.id)?'<span class="chip">✓ Done</span>':''}</div></button>`).join('')||'<div class="card">No adventures match those filters.</div>';document.querySelectorAll('.item').forEach(b=>b.onclick=()=>choose(+b.dataset.id))}
document.querySelectorAll('.cat[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderList();get('list').scrollIntoView({behavior:'smooth'})})
;['search','drive','cost','difficulty','time','dog','unvisited'].forEach(id=>get(id).addEventListener(id==='search'?'input':'change',renderList));
get('favOnly').onclick=()=>{state.favOnly=!state.favOnly;get('favOnly').textContent=state.favOnly?'♥ Showing favorites':'♥ Favorites';renderList()};
function randomPick(){let arr=filtered();if(!arr.length)arr=ADVENTURES;choose(arr[Math.floor(Math.random()*arr.length)].id)} get('surprise').onclick=randomPick;get('surpriseCat').onclick=randomPick;
function choose(id){state.selected=ADVENTURES.find(a=>a.id===id);renderScratch();show('scratch');initScratch()}
function renderScratch(){let a=state.selected;if(!a)return;get('reveal').setAttribute('aria-hidden','true');get('reveal').innerHTML=`<div style="font-size:11px;text-transform:uppercase;letter-spacing:.18em;color:var(--gold)">${a.category}</div><div class="serif" style="font-size:38px;margin-top:6px">${a.name}</div><div class="muted">${a.town}, ${a.state}</div><div class="card" style="margin-top:22px"><b>Mission teaser</b><div style="margin-top:7px">${a.mission}</div></div>`;let g=get('scratchGuide');g.style.display='none';g.onclick=()=>{renderDetails();show('details')}}
function initScratch(){let c=get('scratchCanvas'),box=get('scratchBox'),g=get('scratchGuide'),r=box.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1);c.width=r.width*dpr;c.height=r.height*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);x.fillStyle='#c8a566';x.fillRect(0,0,r.width,r.height);x.fillStyle='#163d2a';x.textAlign='center';x.font='700 20px system-ui';x.fillText('SCRATCH TO REVEAL',r.width/2,r.height/2-8);x.font='14px system-ui';x.fillText('your Carolina adventure',r.width/2,r.height/2+20);let down=false,started=false;c.style.opacity='1';c.style.pointerEvents='auto';function revealReady(){if(!started)return;g.style.display='block';c.style.pointerEvents='none';c.style.opacity='0';get('reveal').setAttribute('aria-hidden','false');g.focus()}function scratch(e){if(!down)return;started=true;let q=c.getBoundingClientRect();x.globalCompositeOperation='destination-out';x.beginPath();x.arc(e.clientX-q.left,e.clientY-q.top,30,0,Math.PI*2);x.fill()}c.onpointerdown=e=>{down=true;started=true;c.setPointerCapture?.(e.pointerId);scratch(e)};c.onpointermove=scratch;c.onpointerup=()=>{down=false;revealReady()};c.onpointercancel=()=>{down=false;revealReady()};c.ontouchend=revealReady;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();started=true;revealReady()}}}
function renderDetails(){let a=state.selected;get('dcat').textContent=a.category;get('dname').textContent=a.name;get('dplace').textContent=`${a.primary} · ${a.town}, ${a.state}`;get('dchips').innerHTML=`<span class="chip">🚗 ~${a.drive} min</span><span class="chip">◷ ${a.time}</span><span class="chip">${a.cost}</span><span class="chip">🥾 ${a.difficulty}</span><span class="chip">🐾 ${a.dog}</span><span class="chip">${a.season}</span>`;get('dmission').textContent=a.mission;get('dfood').textContent=a.food||'Pack a picnic or choose a local stop that fits the day.';get('dbonus').textContent=a.bonus||'Explore nearby.';get('drain').textContent=a.rain||'Check for a nearby museum, café, or indoor attraction.';get('complete').textContent=state.completed.has(a.id)?'✓ Completed':'Mark complete';get('favorite').textContent=state.favorites.has(a.id)?'♥ Saved':'♡ Save';get('heroFav').textContent=state.favorites.has(a.id)?'♥':'♡';get('heroFav').setAttribute('aria-label',state.favorites.has(a.id)?'Remove from saved adventures':'Save this adventure');renderStars()}
get('directions').onclick=()=>{let a=state.selected;window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(`${a.primary} ${a.town} ${a.state}`),'_blank')};get('official').onclick=()=>{if(state.selected?.source)window.open(state.selected.source,'_blank')};get('complete').onclick=()=>{let id=state.selected.id;state.completed.has(id)?state.completed.delete(id):state.completed.add(id);saveState();renderDetails()};function toggleFav(){let id=state.selected.id;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveState();renderDetails()}get('favorite').onclick=toggleFav;get('heroFav').onclick=toggleFav;
function renderStars(){let r=state.selected?state.ratings.get(state.selected.id)||0:0;get('stars').innerHTML=[1,2,3,4,5].map(n=>`<button class="fav" data-star="${n}" aria-label="Rate ${n} star${n===1?'':'s'}" aria-pressed="${n===r}">${n<=r?'★':'☆'}</button>`).join('');document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{state.ratings.set(state.selected.id,+b.dataset.star);saveState();renderStars()})} get('rate').onclick=()=>renderStars();
function renderSaved(){let arr=ADVENTURES.filter(a=>state.favorites.has(a.id));get('savedList').innerHTML=arr.length?arr.map(a=>`<button class="card item savedPick" data-id="${a.id}"><div class="serif" style="font-size:21px">${a.name}</div><div class="muted">${a.town}, ${a.state} · ~${a.drive} min</div></button>`).join(''):'<div class="card">Save adventures with the ♥ button and they will appear here.</div>';document.querySelectorAll('.savedPick').forEach(b=>b.onclick=()=>choose(+b.dataset.id))}
function renderPassport(){let done=ADVENTURES.filter(a=>state.completed.has(a.id));get('doneNum').textContent=done.length;get('pfill').style.width=(done.length/100*100)+'%';let groups=[...new Set(done.map(a=>a.categoryGroup))],defs={waterfalls:['💧','Waterfall Hunter'],towns:['🏘️','Town Explorer'],outdoors:['🌲','Trail Seeker'],history:['🏛️','History Seeker'],culture:['🎵','Culture Curious'],other:['🧭','Curiosity Collector']};get('badges').innerHTML=Object.entries(defs).map(([k,v])=>`<div class="badge" style="opacity:${groups.includes(k)?1:.3}"><div style="font-size:29px">${v[0]}</div><div style="font-size:11px;margin-top:6px">${v[1]}</div></div>`).join('');get('doneList').innerHTML=done.length?done.map(a=>`<div class="card row"><div><div class="serif" style="font-size:19px">${a.name}</div><div class="muted" style="font-size:13px">${a.town}, ${a.state}</div></div><div>${state.ratings.get(a.id)?'★'.repeat(state.ratings.get(a.id)):'✓'}</div></div>`).join(''):'<div class="card">Complete your first adventure and it will appear here.</div>'}
renderList(); if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));